# Generated by Django 5.0.1 on 2024-05-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarGameScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('score', models.IntegerField(default=None)),
            ],
        ),
    ]
