# Generated by Django 5.0.1 on 2024-05-07 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0002_guitargamescores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitargamescores',
            name='name',
        ),
        migrations.AddField(
            model_name='guitargamescores',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guitargamescores',
            name='score',
            field=models.IntegerField(),
        ),
    ]
