# Generated by Django 5.0.1 on 2024-05-07 19:34

import Bar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0003_remove_guitargamescores_name_guitargamescores_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('icon', models.FilePathField(blank=True, default=None, null=True, path=Bar.models.sprite_path)),
                ('top', models.IntegerField(default=0)),
                ('left', models.IntegerField(default=0)),
            ],
        ),
    ]
