# Generated by Django 5.0.1 on 2024-05-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bar', '0005_rename_icon_characters_default_characters_glow'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
